-- Tfumela database hardening migration
ALTER TABLE users ADD COLUMN IF NOT EXISTS country_code CHAR(2);
ALTER TABLE users ADD COLUMN IF NOT EXISTS email_verified_at TIMESTAMPTZ;
ALTER TABLE users ADD COLUMN IF NOT EXISTS password_hash TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS whatsapp_verified_at TIMESTAMPTZ;
ALTER TABLE wallets ADD COLUMN IF NOT EXISTS challenge_nonce TEXT;
ALTER TABLE wallets ADD COLUMN IF NOT EXISTS last_verified_at TIMESTAMPTZ;
ALTER TABLE transfers ADD COLUMN IF NOT EXISTS fee_bps INTEGER;
ALTER TABLE transfers ADD COLUMN IF NOT EXISTS fixed_fee_units NUMERIC(78,0);
ALTER TABLE transfers ADD COLUMN IF NOT EXISTS max_fee_units NUMERIC(78,0);
ALTER TABLE transfers ADD COLUMN IF NOT EXISTS quote_expires_at TIMESTAMPTZ;
ALTER TABLE transfers ADD COLUMN IF NOT EXISTS failure_code TEXT;
ALTER TABLE transfers ADD COLUMN IF NOT EXISTS submitted_at TIMESTAMPTZ;
ALTER TABLE transfers ADD COLUMN IF NOT EXISTS confirmed_at TIMESTAMPTZ;
ALTER TABLE transfers ADD COLUMN IF NOT EXISTS block_number BIGINT;
ALTER TABLE transfers ADD COLUMN IF NOT EXISTS transaction_index INTEGER;
ALTER TABLE transfers ADD COLUMN IF NOT EXISTS log_index INTEGER;
ALTER TABLE transfers ADD COLUMN IF NOT EXISTS contract_address TEXT;
